"""ComfyUI-Liao2049: standalone MiniMax H3 creative node."""

PLUGIN_VERSION = "2026.08.19-public-v1"

from . import h3_dependencies  # registers opt-in dependency diagnostics routes
from .minimax_h3_unified import (
    NODE_CLASS_MAPPINGS as H3_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as H3_NODE_DISPLAY_NAME_MAPPINGS,
)
from .extra_nodes import (
    NODE_CLASS_MAPPINGS as EXTRA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EXTRA_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = dict(H3_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(EXTRA_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS = dict(H3_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(EXTRA_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./js"

print(f"[comfyui-liao2049] loaded {PLUGIN_VERSION}")

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]

